version: '3'

services:
  app:
    build: .
    image: p4d
    container_name: p4d
#    image: wata516/p4d
    restart: always
    environment:
      P4NAME: p4
      P4PORT: 1666
      P4USER: p4admin
      P4PASSWD: p4admin@12345
    working_dir: $PWD
    ports: 
      - "1666:1666"
#    volumes:

#      - $PWD/p4d_volume/servers:/opt/perforce/servers
#      - $PWD/p4d_volume/triggers:/opt/perforce/triggers
#      - $PWD/p4d_volume/etc:/etc/perforce
