version: '3'

services:
  app:
    build: .
    image: p4d
    container_name: p4d
#    image: wata516/p4d
    restart: always
    environment:
      P4NAME: p4
      P4PORT: 1666
      P4USER: p4admin
      P4PASSWD: p4admin@12345
      P4LOG: /p4d/logs
      P4JOURNAL: /p4d/journals
    container_name: "p4d"
    working_dir: $PWD
    ports: 
      - "1666:1666"
    volumes:
      - $PWD/p4d_volume:/p4d
